version: '3.7'

services:

  mfl.app:
    build:
      context: .
      dockerfile: "MyFlickList.App.dockerfile"
    environment:
      ConnectionStrings__Database: "Server=mfl.db;Port=5432;Database=postgres;User ID=postgres;Password=mysecretpassword"
    ports:
      - "5000:80"
    depends_on:
      - "mfl.api"

  mfl.api:
    build:
      context: .
      dockerfile: "MyFlickList.Api.dockerfile"
    ports:
      - "5001:80"
    depends_on:
      - "mfl.db"

  mfl.db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"