
version: '3.7'

services:

  mfl.api:
    build:
      context: .
      dockerfile: "MyFlickList.Api.dockerfile"
    ports:
      - "5001:80"
    depends_on:
      - "mfl.app"

  mfl.app:
    build:
      context: .
      dockerfile: "MyFlickList.App.dockerfile"
    ports:
      - "5000:80"