name: CD

# Change to only run on tags in the future
on: [push]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.100

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Deploy
      run: |
        heroku container:login
        heroku stack:set container -a ${{ secrets.HEROKU_APP }}
        git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}

  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install NodeJS
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12

    - name: Install Netlify CLI
      run: npm i netlify-cli -g

    - name: Pull dependencies
      run: npm ci --no-audit
      working-directory: ./MyFlickList.App

    - name: Build
      run: npm run build
      working-directory: ./MyFlickList.App

    - name: Deploy
      run: netlify deploy --dir=build --prod
      working-directory: ./MyFlickList.App
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}