name: CD

on:
  push:
    tags:
    - '*'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.100

    - run: echo TODO

  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install NodeJS
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12

    - name: Pull dependencies
      run: npm ci --no-audit
      working-directory: ./MyFlickList.App

    - run: echo TODO